### ISSUE TITLE
How do you use this feature?

### ISSUE THREAD

**Issue by john-aws** [shakram02/bash_beautify#5]
The readme says "It'll work with the default format keyboard binding" but a lot of people will not know what that is, or even what to search for.

Please consider adding explicit instructions for how to use it. Both default key combination, and via the VS Code menus if that's applicable.

Also, it does not seem to work in a new, unnamed file. If I create a new file, do not save it, type in some bash scripting, and set the language mode to 'Shell Script' then neither of the following works:

- format document (shift+option+F), does nothing
- format selection (cmd+K, cmd+F), results in 'Sorry, but there is no formatter for 'shellscript'-files installed."

Thanks.

**Comment by shakram02** [comment]
Unfortunately, I can no longer maintain this project, I changed platforms long time ago

**Comment by john-aws** [comment]
OK, thanks. Please consider [archiving the project](https://blog.github.com/2017-11-08-archiving-repositories/) and update your README and description to make it clear to visitors that it’s no longer maintained and it's no longer possible to contribute.

**Comment by shakram02** [comment]
I will, thank you
